version: '2'
services:
  seafile:
   # image: sabaitech/seafile:latest
    build: .
    container_name: seafile
    ports:
      - "8000:8000"
      - "8082:8082"
    environment:
      - SERVER_ADDRESS=my.domain.com
      - SEAFILE_ADMIN=toto
      - SEAFILE_ADMIN_PASSWORD=toto
    volumes:
      - ./seafile:/seafile
